#:kivy 2.1.0

#:import NoTransition kivy.uix.screenmanager.NoTransition
#:include screen_main.kv
#:include screen_counter.kv

# ScreenManager:
<RootScreen>:
    id: screen_manager
    transition: NoTransition()
       
    ScreenMain:
        id: screen_main
        name: 'screen_main'
        screen_manager: screen_manager

    ScreenCounter:
        id: screen_counter
        name: 'screen_counter'
        screen_manager: screen_manager
                  
